root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-dev", "-db-type", "sqlite"]
  bin = "./tmp/main"
  cmd = "cd dashboard && npm run build:dev && cd .. && go build -o ./tmp/main cmd/deployd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".mongodb", "bin", "e2e", "js-sandbox", "node_modules", "dist"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*\\.log$", ".*\\.db$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal", "resources", "dashboard/src", "dashboard/public"]
  include_ext = ["go", "js", "jsx", "ts", "tsx", "css", "html", "json"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true